apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: atlas-auth
  namespace: default
data:
  getkrb.sh: {{ .Values.files.getkrb_sh }}
  getmyproxy.sh: {{ .Values.files.getmyproxy_sh }}
  gridpw: {{ .Values.grid_pw | b64enc }}
  host.cert: {{ .Values.files.grid_crt }}
  kerberos.keytab: {{ .Values.files.krb_keytab }}
  privkey.pem: {{ .Values.files.grid_key }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: yadageloadtoken
data:
  token: {{ .Values.yadage_load_token | b64enc }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: docker-reg-cern
data:
  username: {{ .Values.CERNGitLab.User | b64enc }}
  password: {{ .Values.CERNGitLab.Password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: wflow-shiptarget-ssh
type: Opaque
data:
  id_rsa: |-
    {{ .Values.files.shiptarget_id_rsa }}
  id_rsa.pub: |-
    {{ .Values.files.shiptarget_id_rsa_pub }}
