apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wflow-shiptarget
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wflow-shiptarget
    spec:
      containers:
      - name: shiptarget
        image: recast/sshd
        command: ['/entry.sh','bash','-c','cat /secrets/ssh/id_rsa.pub > /root/.ssh/authorized_keys; /usr/sbin/sshd -D -e -oLogLevel=DEBUG3 -f /etc/ssh/sshd_config']
        volumeMounts:
          - name: ssh
            mountPath: /secrets/ssh
            readOnly: true
          - name: data
            mountPath: /results
            subPath: results
        ports:
          - containerPort: 22
            name: ssh
      volumes:
      - name: ssh
        secret:
          secretName: wflow-shiptarget-ssh
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.wflowserverclaim }}
---
apiVersion: v1
kind: Service
metadata:
  name: wflow-shiptarget
spec:
  type: {{ .Values.InternalServiceType }}
  ports:
  - port: 2022
    targetPort: 22
    name: ssh
  selector:
    app: wflow-shiptarget
