{{ if eq .Values.Storage.Type "localfs"}}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-pv-infra
  labels:
    component: infra
    target: infra
spec:
  capacity:
    storage: {{ .Values.Storage.InfraSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.Storage.HostFS.InfraPath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-pv-wflowworker
  labels:
    component: infra
    target: wflowworker
spec:
  capacity:
    storage: {{ .Values.Storage.WorkerSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.Storage.HostFS.WorkerPath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-pv-wflowserver
  labels:
    component: infra
    target: wflowserver
spec:
  capacity:
    storage: {{ .Values.Storage.WorkflowSvcSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.Storage.HostFS.WorkflowSvcPath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-pv-yadagesvc
  labels:
    component: infra
    target: yadagesvc
spec:
  capacity:
    storage: {{ .Values.Storage.YadageSvcSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.Storage.HostFS.YadageSvcPath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-pv-cc
  labels:
    component: infra
    target: recast-control-center
spec:
  capacity:
    storage: {{ .Values.Storage.CCSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.Storage.HostFS.CCPath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-pv-frontend
  labels:
    component: infra
    target: recast-frontend
spec:
  capacity:
    storage: {{ .Values.Storage.FrontendSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.Storage.HostFS.FrontendPath }}
{{end}}
