apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: shared
provisioner: manila-provisioner
parameters:
  type: "Geneva CephFS Testing"
  zones: nova
  osSecretName: os-trustee
  osSecretNamespace: kube-system
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: csi-cephfsplugin
